name: my-t1open-school
services:
  t1open-school-db:
    image: postgres:17
    container_name: t1open-school-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: t1open-school-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      t1open-school:
        aliases:
          - "t1open-school-db"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: t1open-school-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      t1open-school:
        aliases:
          - "zookeeper"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: t1open-school-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Настройки слушателей - внешний и внутренний доступ
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      # Настройки идемпотентности продюсера
      KAFKA_ENABLE_IDEMPOTENCE: "true"
      KAFKA_TRANSACTIONAL_ID_EXPIRATION_MS: 604800000

      # Настройки offsets
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      # Настройки для работы с транзакциями
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      t1open-school:
        aliases:
          - "kafka"
volumes:
  postgres_data:
networks:
  t1open-school:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.55.1.0/24